tiiuae/sbomnix

Makefile, sbomnix/nix.py
This change, together with the previous commit: b0160de428522efd8b4c96b6c99a18bbdd053976 enable CI testing with travis.
=> Enable CI testing

.github/workflows/test_sbomnix.yml, .travis.yml, nixgraph/graph.py, nixgraph/main.py, sbomnix/utils.py, tests/test_sbomnix.py
This PR makes the following changes to nixgraph:
- Add a command line argument 'inverse' to allow drawing inverse graphs starting from specified nodes
- Add support for csv output format
- Add pytest tests for nixgraph
=> nixgraph: command line argument to draw inverse graphs

nixgraph/graph.py, sbomnix/cpe.py, sbomnix/derivation.py, sbomnix/main.py, sbomnix/sbomdb.py
This PR adds 'dependencies' section to SBOM:
- Read package dependencies using nixgraph
- Start using purl as bom-ref: purl is also used to reference packages in the 'dependencies' section
Other, smaller improvements:
- Move sbomdb to its own module
- Move cpe generation to derivation.py
- Change the derivation.py so that so that derivations without version information are no longer skipped
=> sbomnix: add dependencies to sbom

flake.lock, flake.lock.license, flake.nix
* pip3 install -r requirements.txt would require sudo on NixOS
* nix develop support is just python template from https://github.com/rdk31/nix-flake-templates with flake.nix and flake.lock tested on NixOS. nix develop replaces the first part of https://github.com/tiiuae/sbomnix#running-without-installation on NixOS to test the sbomnix without installation
Signed-off-by: Ville Ilvonen <ville.ilvonen@unikie.com>
=> flake: support for nix develop in NixOS env

nixgraph/main.py, sbomnix/main.py, sbomnix/sbomdb.py, sbomnix/utils.py, setup.py
- Use https://github.com/pypa/setuptools_scm/#setuptools_scm to extract the program's version string. The new version string format is specified in: https://github.com/pypa/setuptools_scm/#default-versioning-scheme. 
As an example "`0.1.dev45+g13df478.d20230116110627`" means:
- `0.1`:               next version
- `dev45`:             dev version, 45 revisions from lastest tag
- `g`:                 scm letter, g for git
- `13df478`:           git revision hash
- `d`:                 datetime letter
- `20230116110627`:    revision datetime stamp in format `YYYYMMDDHHMMSS`
- Use the new version string in cdx sbom tool section
- Add command line argument to print out the program version
=> sbomnix: add githash to cdx tool version string

sbomnix/nix.py, sbomnix/sbomdb.py, sbomnix/utils.py
- `sbomdb.py`: fix regex that matches dependency source paths: this fix impacts dependencies-section in the output cdx. Also, expand the comment that explains why some dependencies might get dropped based on manually analyzing such instances.
- `nix.py`: get rid of the lambda in `_find_outputs` and replace it with a function instead. Let `_find_deriver` handle the missing deriver, instead of handling that in the labmda (now a function) before calling `_find_deriver`
- `nix.py`: change `_find_deriver` function so that it can return `None` in case no derivation was found
- `utils.py`: add `raise_on_error` parameter to `exec_cmd` to allow executing shell commands that might err out, without raising exceptions when that happens
=> sbomnix: fixes from manual sbom verification

Makefile, README.md, doc/nixgraph.md
- Change documentation to instruct pip 'user' install
- Change relevant Makefile targets to also state user install
=> Explicit pip user install

sbomnix/utils.py, scripts/vulnscan/osv.py, scripts/vulnscan/vulnscan.py
This commit adds the following scripts:
- ´osv.py´: demonstrates querying OSV data given CycloneDX SBOM as input.
OSV database currently does not support nix ecosystem, so queries that
specify nix as ecosystem would fail. ´osv.py´ sends queries to OSV
API without specifying the ecosystem, only the package name
and version. Currently, such queries return vulnerabilities
that match the given package and version across all ecosystems.
This tool thus demonstrates using OSV with nix SBOMs.
- ´vulnscan.py´: demonstrates running vulnerability scans with vulnix,
grype, and osv.py given a target nix artifact. The tool generates a
report that summarizes the vulnerabilities found for the given target
with the three scanners.
Example output from scanning both buildtime and runtime dependencies of …
=> vulnscan: initial commit

nixgraph/main.py, sbomnix/main.py, scripts/vulnscan/vulnscan.py
- Use pathlib type for the NIX_PATH command-line argument in sbomnix and nixgraph.
- Fix error trace in vulnscan.py TARGET check
=> sbomnix, nixgraph: use pathlib for NIX_PATH argument

nixgraph/graph.py, sbomnix/cpe.py, sbomnix/derivation.py, sbomnix/nix.py, sbomnix/sbomdb.py, sbomnix/utils.py
- sbomnix: allow multiple out paths per derivation
- sbomnix: simplify store derivation caching
- sbomnix: output valid SBOM also in case the given target has no dependencies
- nixgraph: gracefully handle the case when the given target has no dependencies, simply opt to not draw anything
- utils: make the utils function that can be used to pretty-print a dataframe to use logging instead of directly printing to stdout
=> sbomnix: nixgraph: miscellaneous fixes

README.md, flake.nix
Hey there!
Caught wind of this, and wanted to add a quick flake tweak so `sbomnix` is runnable for for outside folks. This would make so anyone could more easily scan their own nix builds without explicit installation.
This would make it so folks could:
```sh
nix run github:tiiuae/sbomnix/main <your-nix-build>
```
You can test this today as
```sh
nix run github:emattiza/sbomnix/chore/add-package-to-flake <your-nix-build>
```
until it is merged if you want to try for yourself.
=> enhancement: make sbomnix flake runnable

README.md, default.nix, flake.lock, flake.nix, scripts/vulnscan/README.md, shell.nix
- Make flakes.nix import default.nix or shell.nix depending on target
- Update flake.lock
- Update relevant documentation
- Update sbomnix version to 1.1.0
=> sbomnix: rework nix flakes support

Makefile, doc/nixgraph.md, flake.nix, requirements.txt, scripts/vulnscan/vulnscan.py, shell.nix
Fixes after manual testing on a nixos system:
- Makefile: /bin/bash might not exist in the host system, so set the makefile shell variable to 'bash' instead of '/bin/bash'
- Add python requests as a (dev) dependency since it's required by osv.py which demonstrates the usage of OSV data with nix packages
- nixgraph.md: use wget out-paths in the examples
- Fix some typos in the comments
=> misc: fixes from manual testing on nixos

default.nix, doc/nixgraph.md, sbomnix/derivation.py, sbomnix/nix.py, sbomnix/sbomdb.py, tests/compare_deps.py, tests/test_sbomnix.py
- Fix an issue in finding drv runtime dependencies which could have
caused not finding all out-paths associated to deriver
- Sort outpaths under the SBOM component properties in a predictable order
to allow comparing SBOMs produced for the same target in different
invocations of sbomnix
- Fix compare_deps.py to make it work with SBOMs that include components
that have more than one out-paths
- Make the pytest that compares SBOMs for the same target use SBOMs that
include both buildtime and runtime dependencies to include more
components to the compared SBOMs, thus, hopefully catching more errors
- Fix some spelling errors in documentation
- Up the version to 1.2.0
=> sbomnix: fix issue in finding drv out-paths

README.md, default.nix, flake.nix, sbomnix/derivation.py, sbomnix/sbomdb.py, scripts/vulnxscan/README.md, scripts/vulnxscan/__init__.py, scripts/vulnxscan/osv.py, scripts/vulnxscan/vulnxscan.py, setup.py
Improve vulnscan demo:
- Rename vulnscan to vulnxscan
- setup.py: install entry point for vulnxscan
- Add flake target for vulnxscan
- vulnxscan.py: allow using SBOM as input
In addition, this PR adds the following fix:
- derivaiton.py: do not add drv store path as outpath
=> Improve vulnscan demo

.github/workflows/test_sbomnix.yml, .travis.yml, Makefile, pytest.ini, scripts/vulnxscan/README.md, tests/test_sbomnix.py
- Add pytests for vulnxscan
- Add initial tests for sbomnix and nixgraph testing running them as flake
- Make pylint tests execute faster by running the tests with a single command as opposed to invoking pylint separately for each target file
- Allow skipping pytests in CI runs with '@pytest.mark.skip_in_ci'. For now, use this mark to skip vulnxscan scan tests in CI due to grype run failing in github actions test run
- Fix a typo in vulnxscan readme
=> vulnxscan: add initial pytests for vulnxscan

.github/workflows/release_sbomnix.yml, .github/workflows/test_sbomnix.yml, Makefile, README.md, default.nix
- Upload runtime and buildtime SBOMs from sbomnix itself to release artifacts on every push of a new release tag
- Up the sbomnix version to v1.3.0
=> Upload sbomnix sbom to github release artifacts

LICENSES/CC-BY-3.0.txt, Makefile, README.md, nixgraph/graph.py, sbomnix/main.py, sbomnix/sbomdb.py, tests/compare_sboms.py, tests/resources/README.md, tests/resources/spdx_bom-2.3.schema.json, tests/resources/spdx_bom-2.3.schema.json.license, tests/test_sbomnix.py
Add support for sbom output in spdx json format
- sbomnix: support spdx json output (--spdx) argument
- test: add relevant test cases to validate spdx output
- include spdx documents from sbomnix itself to release assets
- fix relevant documentation
In addition this commit includes a fix to Makefile to prune python eggs from the list of python targets.
=> sbomnix: add support for sbom output in spdx json format

.travis.yml, Makefile, README.md, default.nix, flake.lock, scripts/vulnxscan/vulnix.nix, scripts/vulnxscan/vulnxscan.py, shell.nix
- Make grype and vulnix dependencies explicit
- Flake update
- Use pip in place of pip3 in documentation and Makefile
- Up the version to 1.4.1
=> vulnxscan: make grype and vulnix depenendencies explicit

shell.nix
This commit fixes an issue that made the sbomnix nix development shell not trigger the venvShellHook. This issue was introduced in commit: 60c81a4de4249142c763b657bae6063b8500d6fc.
=> sbomnix: fix nix dev shell

Makefile, default.nix, sbomnix/derivation.py, sbomnix/sbomdb.py, tests/compare_deps.py, tests/test_sbomnix.py
Improve derivation attributes:
- Make derivation pname more accurate e.g. for perl packages.
- Do not generate purl or cpe for packages with pname 'source'. Pname 'source' has a special meaning in in Nix - it is the default name for all fetchFromGitHub derivations.
- Add 'urls' attribute, which contains the package fetch url (if any).
- Add license and other meta information to the sbomnix release asset SBOMs.
In addition, this PR includes the following other changes:
- Add a test case that checks the nix-shell works as expected to prevent cases like https://github.com/tiiuae/sbomnix/pull/44 in the future.
- Read 'unfree' and 'description' from each nix package meta information if available.
- Add more properties to SPDX sbom: package summary, downloadLocation.
- Add more properties to …
=> derivation.py: improve derivation attributes

.gitignore, requirements.txt, scripts/repology/README.md, scripts/repology/__init__.py, scripts/repology/repology_cli.py
This PR adds a command line tool to demonstrate querying [repology](https://repology.org/) package information.
For more details, see the README.md included in this PR.
For now, consider `repology_cli` as a demonstration or proof-of-concept. It's already helpful in many ways, but it's clear more work is required, at least:
- repology_cli is missing all automated tests currently. It's gone through some manual testing, but there's very likely bugs here and there
- The implementation should be split into smaller modules
- It might be worth moving repology_cli to its own repository, since it's really not related to sbomnix
=> repology_cli: command line client to query repology.org

scripts/nixupdate/README.md, scripts/nixupdate/__init__.py, scripts/nixupdate/nix-visualize.nix, scripts/nixupdate/nix_outdated.py, shell.nix
This PR adds a command line tool to demonstrate finding outdated nix dependencies for given target in nix out path.
For more details, see the README.md included in this PR.
=> nix_outdated.py: script to list outdated nix dependencies

scripts/vulnxscan/README.md, shell.nix, tests/test_sbomnix.py
- Test case 'test_nixgraph_csv_graph_inverse' assumed the dependency graph for nix package 'hello' had no other leaves except 'libunistring' which is no longer true due to changes in gcc dependencies. Simplify the test by not comparing the full forward and inverse graphs.
- Don't import vulnxscan, nixupdate, or cpedict nix files, but list the dependencies explicitly in the main shell.nix. This makes it easier to develop those scripts in nix devshell.
- Fix vulnxscan usage instructions now that it's no longer installed by setup.py.
=> Fix test_nixgraph_csv_graph_inverse

flake.nix, nixgraph/main.py, sbomnix/main.py, sbomnix/sbomdb.py, sbomnix/utils.py, scripts/nixupdate/README.md, scripts/nixupdate/nix_outdated.py, scripts/nixupdate/nix_secupdates.py, scripts/nixupdate/nixupdate.nix, scripts/repology/repology_cli.nix, scripts/repology/repology_cli.py, scripts/repology/repology_cve.py, shell.nix, tests/test_sbomnix.py
nix_secupdates.py: initial version
- Add nix_secupdates.py script that demonstrates finding potential security updates for nix dependencies. See more details in the [README.md](https://github.com/tiiuae/sbomnix/blob/057ea8b1e0f20982609789778c09efb5d0587279/scripts/nixupdate/README.md#nix_secupdates) section _nix_secupdates_.
- Add repology_cve.py for querying CVEs that impact given package and version. This script is needed by nix_secupdates.py.
- Add support for querying also buildtime packages with nix_outdated.py.
- Import vulnxscan in shell.nix.
- Add more common functions to utils.py.
- Update relevant README.md.
=> nix_secupdates.py: initial version

flake.nix
This is an exciting project, and I cannot wait to see what comes of it.
This PR adjusts `flake.nix` to add outputs for linux `aarch64`, and should make it trivial to add more platforms in the future. Supporting multiple platforms should not complicate development unless running into the dreaded [Import From Derivation](https://nixos.wiki/wiki/Import_From_Derivation).
I have confirmed that tests pass on both `x86_64-linux` and `aarch64-linux`.
I also attempted to get `aarch64-darwin` to work, however it currently fails on `test_nixgraph_csv_graph_inverse` for some reason.
=> Make `flake.nix` support multiple systems

sbomnix/sbomdb.py, sbomnix/utils.py, scripts/vulnxscan/vulnxscan.py
Identify patched vulnerabilities based on 'patches'-field in nix derivation. Matching patches is based on CVE or other vulnerability identifiers in the patch file name. It's a coarse heuristic, but certainly better than nothing.
=> vulnxscan: identify patched vulnerabilities

sbomnix/utils.py, scripts/nixupdate/nix_secupdates.py, scripts/nixupdate/nixupdate.nix
Add '--pr' command-line option to search nixpkgs github for PRs that might include more information concerning the (potentially ongoing) fix for the vulnerability. Adds a URL to best matching PR (if any) to the output table. The PR search takes significant time due to github API rate limits, which is why '--pr' is not enabled by default.
=> nix_secupdates.py: add nixpkgs pr search

nixgraph/graph.py, sbomnix/main.py, sbomnix/nix.py
This PR improves the way sbomnix behaves in case the target derivation isn't realised and runtime dependencies are requested. The issue is described in https://github.com/tiiuae/sbomnix/issues/63.
In essence, this change adds the `--force-realise` option for nix-store query when runtime dependencies are requested.
=> sbomnix: Force-realise runtime dependency paths

Makefile, nixgraph/graph.py, nixgraph/main.py, sbomnix/main.py, sbomnix/sbomdb.py, sbomnix/utils.py, tests/test_sbomnix.py
Add `--depth` option to sbomnix to set the depth of the included dependencies. 
As an example, `--depth=1` indicates the SBOM should include only the direct dependencies. With `--depth=2`, the output SBOM includes the direct dependencies and the first level of transitive dependencies. By default, when `--depth` is not specified, the output SBOM includes all dependencies all the way to the root of the dependency tree.
Implements: https://github.com/tiiuae/sbomnix/issues/70
=> sbomnix: Add --depth command-line option

.github/workflows/release_sbomnix.yml
Add [granular write permission](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) required by [release action](https://github.com/svenstaro/upload-release-action#permissions).
=> gha: Release action needs write permission

tests/test_sbomnix.py
Test `test_nixgraph_csv_graph_inverse` assumed `libunistring` would be a dependency to `hello` package, which might not be always true.
=> tests: Fix test_nixgraph_csv_graph_inverse

flake.lock, nixgraph/graph.py, nixgraph/main.py, sbomnix/cpe.py, sbomnix/derivation.py, sbomnix/main.py, sbomnix/nix.py, sbomnix/sbomdb.py, sbomnix/utils.py, scripts/env.sh, scripts/nixupdate/nix_outdated.py, scripts/nixupdate/nix_secupdates.py, scripts/repology/repology_cli.py, scripts/repology/repology_cve.py, scripts/vulnxscan/osv.py, scripts/vulnxscan/vulnxscan.py, shell.nix, tests/compare_deps.py, tests/compare_sboms.py
Collection of smaller updates, such as:
- Update flake.lock
- Fix nix-shell to re-enable sbomnix editable installation
- Simplify logging
- Cleanup derivation.py for unneeded leftovers from vulnix
=> Misc updates

nixgraph/main.py, sbomnix/main.py, sbomnix/nix.py, sbomnix/utils.py, scripts/env.sh, scripts/nixupdate/nix_outdated.py, scripts/nixupdate/nix_secupdates.py, scripts/vulnxscan/vulnxscan.py
Allow running sbomnix, nixgraph, vulnxscan, nix_outdated, and nix_secupdates without realising the target output if `--buildtime` was requested.
This change also adds another fix (on top of 8de1be529f500332d259f32c10064b59f977e9be) to allow installing sbomnix tooling in nix development shell in editable mode.
=> Allow running sbomnix without realising out paths

scripts/vulnxscan/vulnxscan.py
- When invoking `repology_cli` as a command the `.py` extension is no longer required.
- When invoking `repology_cve` as a command the `.py` extension is no longer required.
=> fix: repology command references in vulnxscan

Makefile, README.md, src/nixupdate/nix_outdated.py, src/sbomnix/main.py, src/sbomnix/sbomdb.py, src/vulnxscan/vulnxscan_cli.py, tests/compare_deps.py, tests/test_sbomnix.py
Remove `--type` command-line argument from sbomnix replacing it with `--buildtime` argument to align the command-line usage with other tools in this repository. Also, update relevant documentation and tests.
Note: this change breaks the command line usage of the `sbomnix` tool for those users who use the `--type` argument, and it should be replaced as follows:
- `--type=buildtime` should be replaced with `--buildtime` after this change
- `--type=both` should be replaced with `--buildtime` after this change
- `--type=runtime` is still the default mode (i.e. the absence of `--buildtime`)
=> sbomnix: Remove command-line argument: --type

.github/workflows/release_sbomnix.yml, Makefile, README.md, doc/nix_outdated.md, doc/nixgraph.md, doc/nixmeta.md, doc/vulnxscan.md, nix/apps.nix, nix/devshell.nix, nix/packages.nix, setup.py, src/common/utils.py, src/nixgraph/main.py, src/nixmeta/__init__.py, src/nixmeta/main.py, src/nixmeta/scanner.py, src/nixupdate/nix_outdated.py, src/sbomnix/cpe.py, src/sbomnix/derivation.py, src/sbomnix/main.py, src/sbomnix/meta.py, src/sbomnix/nix.py, src/sbomnix/sbomdb.py, src/vulnxscan/vulnxscan_cli.py, tests/test_sbomnix.py
This change improves the way sbomnix reads nixpkgs metadata:
- Adds command-line tool and python library `nixmeta`, which allows summarizing nixpkgs meta-attributes from the given nixpkgs version.
- Start using local nix metadata cache generated with `nixmeta` based on the given sbomnix target. Additionally, if available, pre-populate the meta cache from an online database, maintained and daily-updated on github.
Made possible by the above changes, this PR removes the `sbomnix` command-line argument `--meta`: meta-information is now automatically added for all sbomnix SBOMs. 
Also worth noting is that this PR changes `sbomnix`, `nixgraph`, `vulnxscan`, and `nix_outdated` so each tool allows specifying the target as [Nix flake reference](https://nixos.org/manual/nix/stable/command-ref/new-c …
=> Improve integration with nixpkgs metadata

src/sbomnix/sbomdb.py
Such as `file:///nix/store/ww3v2am80v01yy74nfwbik1irnvg0qzp-CVE-2021-3500+CVE-2021-32490+CVE-2021-32491+CVE-2021-32492+CVE-2021-32493.patch`
=> Support for patches that resolve multiple issues

Makefile, src/common/utils.py, src/nixmeta/scanner.py, src/sbomnix/nix.py
Add `extra-experimental-features` into executed nix commands to support running sbomnix tools on nix installations where flakes and nix-command are not enabled.
=> Add extra-experimental-features to nix commands

src/common/utils.py
Fix an issue with utils.py:parse_version, which could result passing an invalid version string to
packaging.version.parse and potentially throwing an invalid version exception.
=> utils: Fix potentially invalid version

src/sbomnix/derivation.py, src/sbomnix/nix.py
Do not assume the derivation's `out` output should always be in the `derivation.py:Derive` outputs list. Instead, only add the outputs of the actually-used outputs.
This change fixes: https://github.com/tiiuae/sbomnix/issues/108.
=> sbomnix: Do not assume out output is always used

src/repology/repology_cli.py, src/repology/repology_cve.py, src/vulnxscan/vulnxscan_cli.py
Increase CachedLimiterSession expiration timeout from two to six hours
=> Increase local http cache timeout

src/provenance/main.py
Hardcoding the derivation path into `externalParameters` is not always desired. It can be added manually into the environment variable if so decided by the user.
=> Don't add derivation path to externalParameters by default

src/sbomnix/meta.py
Gracefully handle the case where the call to nixref_to_nixpkgs_path returns None.
=> sbomnix/meta.py: Allow None in nixpkgs path

nix/packages.nix, src/nixmeta/scanner.py
Avoid hard-coding the `nixpkgs` flakeref to `github:NixOS/nixpkgs` in order to handle alternate `nixpkgs` locations.
=> support different nixpkgs locked types

src/provenance/main.py
This PR gives the provenance generator ~60x speed increase when generating recursive provenance for a big system image, from 5 minutes to 5 seconds, without removing any data. In fact, the detail of the provenance is even increased now with the addition of `--include-outputs` flag, adding previously missing dependencies to the array.
The nix commands themselves are fast but the `subprocess.run()` calls for every dependency in the loop was causing significant overhead. Upon reading the nix docs I found out that you can pass as many derivations as you want in one nix-store query, and you will get the result for all of them, so we can compute all hashes before the loop in single command.
=> Optimize provenance generation speed

nix/packages.nix
`buildPythonPackage` already [accepts makeWrapperArgs](https://github.com/NixOS/nixpkgs/blob/8ef21e88b600a3a2f7403da0275d54dab1400fef/pkgs/development/interpreters/python/mk-python-derivation.nix#L111-L113) which then get applied as part of the [wrap python scripts shell hook](https://github.com/NixOS/nixpkgs/blob/8c116c6112f09a538b8b20db8938a42942a6d88b/pkgs/development/interpreters/python/wrap.sh#L82-L94)
Cleans up the bin directory a bit:
```
[23:20:01] jringer@jringer-5560-nixos ~/work/sbomnix (avoid-double-wrapping)
$ ls -a ./result/bin/
.nix_outdated-wrapped  .provenance-wrapped    .sbomnix-wrapped    nixgraph    repology_cli  vulnxscan
.nixgraph-wrapped      .repology_cli-wrapped  .vulnxscan-wrapped  nixmeta     repology_cve  
.nixmeta-wrapped       .repology_cve-wrapped …
```
=> Avoid double wrapping

src/sbomnix/cdx.py, src/sbomnix/sbomdb.py
Trying to chunk up cdx1.4 work into more reviewable bites. This is just moving cdx utilities into another file.
=> Move cdx utils to separate file

src/sbomnix/cdx.py, src/sbomnix/main.py, src/sbomnix/sbomdb.py, src/vulnxscan/utils.py, src/vulnxscan/vulnxscan_cli.py, tests/resources/README.md, tests/resources/cdx_bom-1.4.schema.json, tests/test_sbomnix.py
Get vulnerabilities  enumerated for CDX 1.4 scans.
I did check this was CDX 1.4 compliant (which it is), but still missing a `signatures` field. However, a lot of CDX additions are optional. And support for signatures can be added later.
=> CDX 1.4, Initial support

src/sbomnix/sbomdb.py
To match upstream spec https://cyclonedx.org/docs/1.4/json/#metadata_properties_items_value
=> CDX: ensure metadata property is a string

src/sbomnix/cdx.py
Library is the preferred default according to the spec: https://cyclonedx.org/docs/1.4/json/#components_items_type
=> CDX: use library as component default

nix/packages.nix, setup.py, src/common/utils.py, src/sbomnix/cpe.py, src/sbomnix/dfcache.py, src/sbomnix/meta.py
Use [FileLock](https://github.com/tox-dev/filelock) to synchronize access to the shared dataframe cache to allow running sbomnix concurrently.
Remove retry logic introduced in https://github.com/tiiuae/sbomnix/pull/118 as it's now unnecessary.
=> Fix DataFrameDiskCache locking

src/sbomnix/main.py
Exposes `--include-vulns` flag in the `sbomnix` cli so users can enable/disable including vulnerabilities in CycloneDX SBOMs
=> sbomnix: expose `--include-vulns` flag

src/sbomnix/sbomdb.py
PR https://github.com/tiiuae/sbomnix/pull/133 removed the `vulnix` scan from CDX sbom, because it introduced NaNs in bom-ref for findings in vulnerabilities section. This PR re-enables the `vulnix` scan for the CDX sbom, removing the NaN bom-refs by doing an 'inner' instead of 'left' join between the vulnerabilities and the sbom package names and versions.
=> Re-enable vulnix scan for CDX vulns

src/sbomnix/nix.py
Remove unnecessary optimization from sbomnix, which broke the `sbomnix` command line option `--depth` when used together with `--buildtime` option.
The removed optimization caused `--buildtime` sboms to always include the full closure (all buildtime dependencies) even if `--depth` was specified, requesting dependencies only up until specified depth in the dependency graph.
=> Fix sbomnix --depth with buildtime dependencies

src/vulnxscan/osv.py
OSV API now requires the package version and would return an error status in case the package version is missing.
=> osv: Skip osv query if package version is unknown

nix/checks.nix, nix/devshell.nix, nix/packages.nix
Remove duplicate package lists in `nix/packages.nix` and `nix/devshell.nix`
=> Cleanup sbomnix nix package

default.nix, flake.nix, nix/apps.nix, nix/checks.nix, nix/devshell.nix, nix/packages.nix, nix/treefmt.nix, shell.nix
Start using [nixfmt](https://github.com/NixOS/nixfmt) as nix formatter.
This should be merged after https://github.com/tiiuae/sbomnix/pull/143.
=> Use nixfmt nix formatter

Makefile, nix/packages.nix, pytest.ini, tests/test_sbomnix.py
Improve pytest test execution time:
- Run pytest tests in parallel
- Add a Makefile target `test-smoke` to allow running a quick test against sbomnix tools
Should be merged after https://github.com/tiiuae/sbomnix/pull/146.
=> Improve pytest test execution time

src/sbomnix/cdx.py
Set the cdx component type based on the following heuristic:
- Set the default component type to 'library'
- Set the component type to 'file' if the drv version string is missing
Resolves: https://github.com/tiiuae/sbomnix/issues/140
=> Classify cdx component type file

src/nixmeta/scanner.py, src/sbomnix/meta.py
- Do not attempt to read the nix meta info from `_NIXMETA_CSV_URL`; instead, always generate the meta with `nix-env` caching it locally
- When running `nix-env`, use `--arg config {allowAliases=false};` to ensure no aliases are in the results. This gets rid of the evaluation warnings that earlier occurred when the local meta cache was updated.
=> Stop using nixmeta csv, ensure no aliases in meta

src/common/utils.py
When running sbomnix as a Nix build (in the Nix sandbox), network access is restricted.
This prevents name resolution, which fails (somehow) with an URLError. Let's handle them the same way HTTPError is.
```
Traceback (most recent call last):
File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/urllib/request.py", line 1319, in do_open
h.request(req.get_method(), req.selector, req.data, headers,
~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
encode_chunked=req.has_header('Transfer-encoding'))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/nix/store/sd81bvmch7njdpwx3lkjslixcbj5mivz-python3-3.13.4/lib/python3.13/http/client.py", line 1338, in request
self._send_request(method, url, body, headers, encode_chunked) …
```
=> Also ignore "URL" errors when fetching assets

src/common/utils.py, src/nixmeta/scanner.py, src/sbomnix/nix.py, src/vulnxscan/vulnscan.py
Change `utils.exec_cmd()` to log error by default, still making it possible for the caller to explicitly ask to not log errors to cover cases where errors are expected. Before this PR, the error was only logged if verbosity was set to DEBUG or more verbose which hid important details on unexpected errors.
=> Improve exec_cmd logging

src/vulnxscan/osv.py
Skip osv parse if 'vulns' is missing from the batch query response.
=> vulnxscan: Skip osv parse if vulns is missing
