.github/workflows/test_sbomnix.yml

Enable github actions CI

---

Makefile
sbomnix/main.py

Make clean clean pytest cache, fix sbomnix vendor name

---

.gitignore
Makefile
README.md
nixgraph/__init__.py
nixgraph/graph.py
nixgraph/main.py
requirements.txt
sbomnix/utils.py
scripts/env.sh
setup.py

Add nixgraph: utility that allows visualizing nix dependency graphs

nixgraph: initial commit

---

requirements.txt
sbomnix/sbomdb.py
setup.py

sbomnix: sbom: extract and validate spdx licenses

---

README.md

README.md: mention Ghaf project in the main readme

---

nixgraph/graph.py
sbomnix/sbomdb.py

- nixgraph: output graph nodes in predictable order
- sbomnix: output sbom components in alphanumeric order

sbom components and nixgraph nodes in predictable order

---

sbomnix/sbomdb.py

sbomnix: add timestamp to cdx sbom

---

sbomnix/sbomdb.py

sbomnix: add nix out and drv paths to cdx sbom

---

Makefile

Makefile: add target to remove all untracked files

---

sbomnix/sbomdb.py

Add sbom type (buildtime or runtime) in the top-level metadata properties section.

sbomnix: add sbom type to cdx sbom

---

README.md
sbomnix/sbomdb.py

- README.md: fix table of contents
- sbomdb.py: change sbomndb init default to runtime

doc: fix toc in main readme

---

README.md
scripts/vulnscan/README.md

doc: add vulnscan documentation

---

nixgraph/graph.py

This change is needed to handle the unlikely case where nix store is not '/nix/store/'.

nixgraph: dynamically read nix store path

---

default.nix
sbomnix/derivation.py
shell.nix

sbomnix: add default.nix and shell.nix

---

default.nix
shell.nix

Add grype as dependency to sbomnix

---

README.md
doc/nixgraph.md
scripts/vulnxscan/README.md

doc: fix installation instructions

---

README.md
default.nix
flake.lock
shell.nix

- Fix uninstall instructions
- Add curl dependency
- Update flake lock file
- Up the version to 1.4.3

sbomnix: release 1.4.3

---

scripts/vulnxscan/vulnxscan.py

vulnxscan: handle unicode derrors in json

vulnxscan: handle unicode derrors in is json

---

scripts/vulnxscan/vulnxscan.nix
scripts/vulnxscan/vulnxscan.py

This PR fixes the following error report: https://github.com/tiiuae/sbomnix/issues/56

vulnxscan: fix issue with json file as nix artifact

---

LICENSES/CC-BY-SA-4.0.txt
README.md
doc/img/git_r2_col.svg.license
doc/img/git_r2_col_inv.svg.license
doc/img/wget_b1.svg.license
doc/img/wget_r1.svg.license
doc/img/wget_r1_paths.svg.license
doc/img/wget_r2.svg.license
doc/img/wget_r2_col.svg.license
doc/img/wget_r2_inv.svg.license
doc/img/wget_runtime.svg.license
doc/nixgraph.md
scripts/nixupdate/README.md
scripts/repology/README.md
scripts/vulnxscan/README.md
tests/resources/README.md

Change documentation license to CC-BY-SA-4.0

Change documentation license to CC-BY-SA-4.0

---

.github/workflows/check-commit-message.yaml
README.md
githooks/check-commit.sh
githooks/check-commits.sh
githooks/install-git-hooks.sh

Add git hooks and GitHub Action for checking commit messages.

Add githooks for checking commit messages

---

.github/workflows/release_sbomnix.yml
.github/workflows/test_sbomnix.yml
README.md
doc/nixgraph.md
flake.lock
flake.nix
sbomnix/utils.py
scripts/nixupdate/README.md
scripts/nixupdate/nix_secupdates.py

This PR makes the following updates/fixes:
- Update flake.lock
- gha: Remove unneeded graphviz installation
- gha: Use nix flakes when running github actions
- gha: Update cachix/install-nix-action to current newest version
- utils.py: Minor improvements to version regexps
- flake.nix: Quote nixpkgs URL
- Minor fixes to documentation

sbomnix: Misc updates

---

sbomnix/sbomdb.py

Fix candidate for https://github.com/tiiuae/sbomnix/issues/79

sbomnix: Fix parsing json meta entries

---

default.nix
requirements.txt
sbomnix/derivation.py
setup.py

- Fix pycodestyle error: "[E721 do not compare types](https://www.flake8rules.com/rules/E721.html)" triggered from derivation.py: https://github.com/tiiuae/sbomnix/actions/runs/5712885824/job/15477228569.
- Add python packaging dependency

sbomnix: Fix pycodestyle error

---

tests/compare_deps.py

Fixes to tests after testing on `x86_64-darwin`.

tests: fix compare_dependencies

---

README.md
flake.lock
scripts/nixupdate/nixupdate.nix
scripts/repology/repology_cli.nix
scripts/vulnxscan/vulnxscan.nix

- Flake update
- Fix issues with duplicate dependencies to sbomnix
- Main README.md: add a reference to https://github.com/tiiuae/ghafscan

Flake update

---

nixgraph/graph.py
sbomnix/cpe.py
sbomnix/nix.py
sbomnix/utils.py
scripts/vulnxscan/README.md
scripts/vulnxscan/osv.py
scripts/vulnxscan/vulnxscan.py

Add severity to vulnxscan output for vulnerabilities where severity information is available. Severity will be empty if it's not available.

vulnxscan: Add severity

---

README.md
doc/provenance.md
nix/apps.nix
setup.py
src/provenance/__init__.py
src/provenance/main.py
tests/resources/README.md
tests/resources/provenance-1.0.schema.json
tests/test_sbomnix.py

Adds python script to generate provenance file according to SLSA v1 specification, and documentation for it.

Add provenance generation tool

---

doc/provenance.md

Few mistakes slipped through the review

Fix example script in provenance docs

---

src/sbomnix/cpe.py
src/sbomnix/meta.py

The lock can sometimes clash when sbomnix is ran in parallel

Wait and retry when sqlite database is locked

---

nix/devshell.nix
nix/treefmt.nix
src/common/utils.py
src/nixgraph/graph.py
src/nixgraph/main.py
src/nixmeta/main.py
src/nixmeta/scanner.py
src/nixupdate/nix_outdated.py
src/repology/repology_cli.py
src/repology/repology_cve.py
src/sbomnix/cdx.py
src/sbomnix/cpe.py
src/sbomnix/derivation.py
src/sbomnix/dfcache.py
src/sbomnix/main.py
src/sbomnix/meta.py
src/sbomnix/nix.py
src/sbomnix/sbomdb.py
src/vulnxscan/osv.py
src/vulnxscan/utils.py
src/vulnxscan/vulnscan.py
src/vulnxscan/vulnxscan_cli.py
src/vulnxscan/whitelist.py
tests/compare_deps.py
tests/compare_sboms.py
tests/test_sbomnix.py

Start running [isort](https://github.com/PyCQA/isort) in `nix flake check`.
This should be merged after https://github.com/tiiuae/sbomnix/pull/142.

Isort in nix check

---

Makefile
nix/checks.nix
nix/devshell.nix
nix/treefmt.nix
setup.py
src/common/utils.py
src/nixgraph/graph.py
src/nixgraph/main.py
src/nixmeta/main.py
src/nixmeta/scanner.py
src/nixupdate/nix_outdated.py
src/repology/repology_cli.py
src/repology/repology_cve.py
src/sbomnix/cdx.py
src/sbomnix/derivation.py
src/sbomnix/dfcache.py
src/sbomnix/main.py
src/sbomnix/nix.py
src/sbomnix/sbomdb.py
src/vulnxscan/osv.py
src/vulnxscan/utils.py
src/vulnxscan/vulnscan.py
src/vulnxscan/vulnxscan_cli.py
src/vulnxscan/whitelist.py
tests/compare_deps.py
tests/compare_sboms.py

Replace pycodestyle and black with [ruff](https://github.com/astral-sh/ruff).
This should be merged after https://github.com/tiiuae/sbomnix/pull/144.

Use ruff python linter

---

.github/workflows/check-commit-message.yaml
.github/workflows/release_sbomnix.yml
.github/workflows/test_sbomnix.yml
tests/compare_deps.py
tests/test_sbomnix.py

- Start running github test action on `macos-latest` in addition to `ubuntu-latest`
- Update actions/checkout action

Start running github test action on macos

---

src/common/utils.py
src/sbomnix/main.py

This MR allows running the underlying `nix` command using `--impure`

Allow running nix with --impure

---

src/nixmeta/scanner.py

fixes: https://github.com/tiiuae/sbomnix/issues/157

make nixmeta.csv extensible
